export declare const lunarInfo: number[];
export declare const zodiacs: string[];
export declare const Gan: string[];
export declare const Zhi: string[];
export declare const weekday: string[];
export declare const sTermInfo: number[];
export declare const solarTerm: string[];
export declare const leapYear: string[];
export interface Calendar {
    gregorianYear?: number;
    gregorianMonth?: string;
    gregorianDay?: string;
    weekday?: string;
    hours?: string;
    minutes?: string;
    seconds?: string;
    lunarYear?: number;
    lunarMonth?: number;
    lunarDay?: number;
    lunarYearCn?: string;
    lunarMonthCn?: string;
    lunarDayCn?: string;
    zodiacYear?: string;
    solarTerm?: string;
    gregorianFestival?: string;
    lunarFestival?: string;
    leapMonth?: number;
    getLeapMonth?: (year: number) => number;
    leapYear?: string;
    isLeapYear?: (date: number) => boolean;
}
