export { filter } from './filter';
export { selects, select } from './select';
export declare function toArray<T>(value: T | T[]): T[];
export declare function isArray(value: any): boolean;
export declare function pick<T>(list: T[]): T;
export declare function unique<T>(list: T[]): T[];
export declare function chunk<T>(list: T[], size: number): T[][];
export declare function concat<T>(...list: T[]): T[];
export declare function drop<T>(list?: T[], n?: number): T[];
export declare function dropRight<T>(list: T[], n?: number): T[];
export declare function fill<T>(array: T[], value: T, num?: number): T[];
export declare function difference<T>(list: T[], ...filterConditions: T[]): T[];
