import * as _ from '..'
import { test } from 'unit-testing-js'

test<any, any>('isFileExtension', _.isFileExtension,
	{ param: 'png', tobe: false },
	{ param: 'jpeg', tobe: false },
	{ param: 'jpg', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'bmp', tobe: false },
	{ param: '.png', tobe: true },
	{ param: '.jpeg', tobe: true },
	{ param: '.jpg', tobe: true },
	{ param: '.png', tobe: true },
	{ param: '.bmp', tobe: true },
	{ param: '123.png', tobe: true },
	{ param: '123.jpeg', tobe: true },
	{ param: '123.jpg', tobe: true },
	{ param: '123.png', tobe: true },
	{ param: '123.bmp', tobe: true },
	{ param: 'name.png', tobe: true },
	{ param: 'name.jpeg', tobe: true },
	{ param: 'name.jpg', tobe: true },
	{ param: 'name.png', tobe: true },
	{ param: 'name.bmp', tobe: true },
	{ param: 'bmp', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'jpeg', tobe: false },
	{ param: 'jpg', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'bmp', tobe: false },
	{ param: 'bmp123', tobe: false },
	{ param: 'png123', tobe: false },
	{ param: 'jpeg123', tobe: false },
	{ param: 'jpg123', tobe: false },
	{ param: 'png123', tobe: false },
	{ param: 'bmp123', tobe: false },
	{ param: 'png.name', tobe: true },
	{ param: 'jpeg.name', tobe: true },
	{ param: 'jpg.name', tobe: true },
	{ param: 'png.name', tobe: true },
);

test<any, any>('isImageFile', _.isImageFile,
	{ name: 'isImage-1', param: '123.png', tobe: true },
	{ name: 'isImage-2', param: '123.jpeg', tobe: true },
	{ name: 'isImage-3', param: '123.jpg', tobe: true },
	{ name: 'isImage-4', param: '123.png', tobe: true },
	{ name: 'isImage-5', param: '123.bmp', tobe: true },
	{ name: 'isImage-6', param: 'name.png', tobe: true },
	{ name: 'isImage-7', param: 'name.jpeg', tobe: true },
	{ name: 'isImage-8', param: 'name.jpg', tobe: true },
	{ name: 'isImage-9', param: 'name.png', tobe: true },
	{ name: 'isImage-10', param: 'name.bmp', tobe: true },
	{ name: 'isImage-11', param: 'namepng', tobe: false },
	{ name: 'isImage-12', param: 'namejpeg', tobe: false },
	{ name: 'isImage-13', param: 'namejpg', tobe: false },
	{ name: 'isImage-14', param: 'namepng', tobe: false },
	{ name: 'isImage-15', param: 'bmp', tobe: false },
	{ name: 'isImage-16', param: 'png', tobe: false },
	{ name: 'isImage-17', param: 'jpeg', tobe: false },
	{ name: 'isImage-18', param: 'jpg', tobe: false },
	{ name: 'isImage-19', param: 'png', tobe: false },
	{ name: 'isImage-20', param: 'bmp', tobe: false },
	{ name: 'isImage-21', param: 'bmp123', tobe: false },
	{ name: 'isImage-22', param: 'png123', tobe: false },
	{ name: 'isImage-23', param: 'jpeg123', tobe: false },
	{ name: 'isImage-24', param: 'jpg123', tobe: false },
	{ name: 'isImage-25', param: 'png123', tobe: false },
	{ name: 'isImage-26', param: 'bmp123', tobe: false },
	{ name: 'isImage-27', param: 'png.name', tobe: false },
	{ name: 'isImage-28', param: 'jpeg.name', tobe: false },
	{ name: 'isImage-29', param: 'jpg.name', tobe: false },
	{ name: 'isImage-30', param: 'png.name', tobe: false },
);

test<any, any>('isH5VideoFile', _.isVideoFile,

	{ param: 'mp4', tobe: false },
	{ param: 'webm', tobe: false },
	{ param: 'ogg', tobe: false },

	{ param: 'name.mp4', tobe: true },
	{ param: 'name.webm', tobe: true },
	{ param: 'name.ogg', tobe: true },

	{ param: 'png', tobe: false },
	{ param: 'jpeg', tobe: false },
	{ param: 'jpg', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'bmp', tobe: false },
	{ param: '.png', tobe: false },
	{ param: '.jpeg', tobe: false },
	{ param: '.jpg', tobe: false },
	{ param: '.png', tobe: false },
	{ param: '.bmp', tobe: false },
	{ param: '123.png', tobe: false },
	{ param: '123.jpeg', tobe: false },
	{ param: '123.jpg', tobe: false },
	{ param: '123.png', tobe: false },
	{ param: '123.bmp', tobe: false },
	{ param: 'name.png', tobe: false },
	{ param: 'name.jpeg', tobe: false },
	{ param: 'name.jpg', tobe: false },
	{ param: 'name.png', tobe: false },
	{ param: 'name.bmp', tobe: false },
	{ param: 'bmp', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'jpeg', tobe: false },
	{ param: 'jpg', tobe: false },
	{ param: 'png', tobe: false },
	{ param: 'bmp', tobe: false },
	{ param: 'bmp123', tobe: false },
	{ param: 'png123', tobe: false },
	{ param: 'jpeg123', tobe: false },
	{ param: 'jpg123', tobe: false },
	{ param: 'png123', tobe: false },
	{ param: 'bmp123', tobe: false },
	{ param: 'png.name', tobe: false },
	{ param: 'jpeg.name', tobe: false },
	{ param: 'jpg.name', tobe: false },
	{ param: 'png.name', tobe: false },
);
test<any, any>('isPdfFile', _.isPdfFile,
	{ param: 'pdf', tobe: false },
	{ param: 'name.pdf', tobe: true },
);

test<any, any>('isWordFile', _.isWordFile,
	{ param: 'name.doc', tobe: true },
	{ param: 'name.docx', tobe: true },
);

test<any, any>('isExcelFile', _.isExcelFile,
	{ param: 'name.doc', tobe: false },
	{ param: 'name.docx', tobe: false },
	{ param: 'name.xls', tobe: true },
	{ param: 'name.xlsx', tobe: true },
	{ param: 'name.csv', tobe: true },
);
