export declare function spLength(value: number | string, min: number | undefined, max: number): string;
export declare function isNumber(value: any): boolean;
export declare function isEffectNumber(num: any): boolean;
export declare function toNumber(value: any): number;
export declare function isFloat(num: number): boolean;
export declare function clamp(num: number, lower?: number, upper?: number): number;
export declare function random(lower?: number, upper?: number, floating?: boolean): number;
export declare function inRange(num: number, start?: number, end?: number): boolean;
export declare function between(num: number, start?: number, end?: number): boolean;
export declare function round(number: number, n?: number): number;
export declare function toThousands(num: string | number): string;
