import { anyToNumberFn } from '../type';
export declare function isEffectNumber(num: number): boolean;
export declare const toNumber: anyToNumberFn;
export declare const isNumber: (value: any) => boolean;
export declare function isFloat(num: number): boolean;
export declare function randomNumByRange(min: number, max: number): number;
export declare function clamp(num: number, lower?: number, upper?: number): number;
export declare function inRange(num: number, start?: number, end?: number): boolean;
export declare function random(lower?: number, upper?: number, floating?: boolean): number;
export declare function between(value: number, start: number, end: number): boolean;
