// export * as rMethods from './method'
// export * as rNumber from './number'
// export * as rString from './string'
// export * as rTime from './time'
// export * as rUtil from './util'
// export * as rArray from './array'
// export * as rObject from './object'
// export * as rFunction from './function'
// export * as rMath from './math'
// export * as rCollection from './collection'
export * as RMethods from './method'
export * as RNumber from './number'
export * as RString from './string'
export * as RTime from './time'
export * as RUtil from './util'
export * as RArray from './array'
export * as RObject from './object'
export * as RFunction from './function'
export * as RMath from './math'
export * as RCollection from './collection'

export * from './method'
export * from './number'
export * from './string'
export * from './time'
export * from './util'
export * from './array'
export * from './object'
export * from './function'
export * from './math'
export * from './collection'
